dist: focal  # Use Ubuntu 20.04 (compatible with latest Node.js and npm)
language: node_js
node_js:
  - "lts/*"  # Use the latest long-term support version of Node.js

install:
  - npm install  # Install project dependencies

script:
  - npm -v  # Check npm version
  - npm install  # Install dependencies
  - npm test  # Run tests

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
