language: node_js
node_js:
  - "stable"

dist: focal

before_install:
  - rm -rf ~/.rvm
  - rm -rf ~/.rbenv
  - sudo apt-get remove --purge ruby

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
