dist: focal  # Use Ubuntu 20.04 (which has the required libraries)
language: node_js
node_js:
  - "lts/*"  # Use the latest long-term support version of Node.js
install:
  - npm install
script:
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
